services:
  openldap:
    image: bitnami/openldap:2.6.9
    container_name: openldap
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=org
      - LDAP_USERS=${LDAP_USERS}
      - LDAP_PASSWORDS=${LDAP_PASSWORDS}
    ports:
      - "1389:1389"
      - "1636:1636"
    volumes:
      - openldap_data:/bitnami/openldap

  vault:
    image: hashicorp/vault:1.19
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    mem_limit: 512m
    volumes:
      - vault-data:/vault/file

volumes:
  openldap_data:
  vault-data:
